name: HawkScan
on:
  push:
    branches:
      - stackhawk
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Docker Build
        run: "docker build -t avinashupadhya99/kubegen:${{ github.run_number }} ."
      - name: Start Application
        run: "docker run -d --rm --name kubegen -p 3000:3000 avinashupadhya99/kubegen:${{ github.run_number }}"
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v1.3.0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}